### PR TITLE
fix #50

### LINKED ISSUE #50: Only one static constructor is generated when multiple types with same DependencyPropertyAttribute in the same file
### Describe the bug

There are several types with DependencyPropertyAttribute  in MainWindow.cs: 

https://github.com/HavenDV/DependencyPropertyGenerator/blob/7cddc3a4d9f01c1dc366f64fb5f4d913fdf9b202/src/tests/DependencyPropertyGenerator.IntegrationTests/MainWindow.cs#L14-L24

https://github.com/HavenDV/DependencyPropertyGenerator/blob/7cddc3a4d9f01c1dc366f64fb5f4d913fdf9b202/src/tests/DependencyPropertyGenerator.IntegrationTests/MainWindow.cs#L145-L152

1. add `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` to **DependencyPropertyGenerator.IntegrationTests.csproj** project
2. build
3. open `H.Generators.StaticConstructorGenerator` folder

image

there's no `H.Generators.IntegrationTests.Generatable.StaticConstructor.g.cs ` file

### Steps to reproduce the bug

1. add `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` to **DependencyPropertyGenerator.IntegrationTests.csproj** project
2. build
3. open `H.Generators.StaticConstructorGenerator` folder

### Expected behavior

generated `H.Generators.IntegrationTests.Generatable.StaticConstructor.g.cs` file correctly.
All static constructor should be generated correctly when multiple types with same DependencyPropertyAttribute in one file

### Screenshots

image

### NuGet package version

_No response_

### IDE

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noliar**
fix #50

### CODE REVIEW

File: src/libs/DependencyPropertyGenerator/Generators/StaticConstructorGenerator.cs [hunk 1]
```diff
@@ -32,55 +33,47 @@ public void Initialize(IncrementalGeneratorInitializationContext context)
...
             .ForAttributeWithMetadataNameOfClassesAndRecords("DependencyPropertyGenerator.AttachedDependencyPropertyAttribute")
             .SelectManyAllAttributesOfCurrentClassSyntax()
             .Combine(framework)
             .Combine(version)
             .SelectAndReportExceptions(static (x, _) => PrepareData(x, isAttached: true), context, Id)
             .WhereNotNull()
-            .CollectAsEquatableArray()
-            .SelectAndReportExceptions(GetSourceCode, context, Id)
-            .AddSource(context);
-        context.SyntaxProvider
```
Comment (HavenDV) [inline src/libs/DependencyPropertyGenerator/Generators/StaticConstructorGenerator.cs:65]: Seems like `DependencyPropertyGenerator.AttachedDependencyPropertyAttribute`1` was missing
